variables:
  MAVEN_OPTS: "-Xmx1536m"
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk

stages:
  - build
  - deploy

maven-build:
  stage: build
  script:
    - "mvn -DskipTests clean package"

maven-deploy:
  stage: deploy
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
    - /^dev$/
