variables:
  MAVEN_OPTS: "-Xmx1536m"

stages:
  - build
  - deploy

maven-build:
  stage: build
  script:
    - "mvn -DskipTests clean package"

maven-deploy:
  stage: deploy
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
