image:
  name: igloo-containers.tools.kobalt.fr/containers/maven-igloo:3.8-openjdk-11

variables:
  MAVEN_OPTS: "-Xmx1536m"

stages:
  - build
  - deploy

maven-build:
  stage: build
  script:
    - "mvn -DskipTests clean package"
  tags:
    - docker

maven-deploy:
  stage: deploy
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
  tags:
    - docker
